/*
  Licensed under the Apache License, Version 2.0
    http://www.apache.org/licenses/LICENSE-2.0.html

  AUTOGENERATED BY H2O at 2021-01-08T19:23:36.174+01:00
  3.30.0.3
  
  Standalone prediction code with sample test data for GLMModel named glm_binomial_prova_pros_retrain

  How to download, compile and execute:
      mkdir tmpdir
      cd tmpdir
      curl http://127.0.0.1:54321/3/h2o-genmodel.jar > h2o-genmodel.jar
      curl http://127.0.0.1:54321/3/Models.java/glm-binomial-prova-pros-retrain > glm_binomial_prova_pros_retrain.java
      javac -cp h2o-genmodel.jar -J-Xmx2g -J-XX:MaxPermSize=128m glm_binomial_prova_pros_retrain.java

     (Note:  Try java argument -XX:+PrintCompilation to show runtime JIT compiler behavior.)
*/
package H2OSpoon;
import java.util.Map;
import hex.genmodel.GenModel;
import hex.genmodel.annotations.ModelPojo;

@ModelPojo(name="glm_binomial_prova_pros_retrain", algorithm="glm")
public class glm_binomial_prova_pros_retrain extends GenModel {
  public hex.ModelCategory getModelCategory() { return hex.ModelCategory.Binomial; }

  public boolean isSupervised() { return true; }
  public int nfeatures() { return 5; }
  public int nclasses() { return 2; }

  // Names of columns used by model.
  public static final String[] NAMES = NamesHolder_glm_binomial_prova_pros_retrain.VALUES;
  // Number of output classes included in training data response column.
  public static final int NCLASSES = 2;

  // Column domains. The last array contains domain of response column.
  public static final String[][] DOMAINS = new String[][] {
    /* AGE */ null,
    /* RACE */ null,
    /* DCAPS */ null,
    /* PSA */ null,
    /* GLEASON */ null,
    /* CAPSULE */ glm_binomial_prova_pros_retrain_ColInfo_5.VALUES
  };
  // Prior class distribution
  public static final double[] PRIOR_CLASS_DISTRIB = null;
  // Class distribution used for model building
  public static final double[] MODEL_CLASS_DISTRIB = null;

  public glm_binomial_prova_pros_retrain() { super(NAMES,DOMAINS,"CAPSULE"); }
  public String getUUID() { return Long.toString(6672809285863010176L); }

  // Pass in data in a double[], pre-aligned to the Model's requirements.
  // Jam predictions into the preds[] array; preds[0] is reserved for the
  // main prediction (class for classifiers or value for regression),
  // and remaining columns hold a probability distribution for classifiers.
  public final double[] score0( double[] data, double[] preds ) {
    final double [] b = BETA.VALUES;
    for(int i = 0; i < 0; ++i) if(Double.isNaN(data[i])) data[i] = CAT_MODES.VALUES[i];
    for(int i = 0; i < 5; ++i) if(Double.isNaN(data[i + 0])) data[i+0] = NUM_MEANS.VALUES[i];
    double eta = 0.0;
    for(int i = 0; i < CATOFFS.length-1; ++i) {
      int ival = (int)data[i];
      if(ival != data[i]) throw new IllegalArgumentException("categorical value out of range");
      ival += CATOFFS[i];
      if(ival < CATOFFS[i + 1])
        eta += b[ival];
    }
    for(int i = 0; i < b.length-1-0; ++i)
    eta += b[0+i]*data[i];
    eta += b[b.length-1]; // reduce intercept
    double mu = hex.genmodel.GenModel.GLM_logitInv(eta);
    preds[0] = (mu >= 0.36126193404189616) ? 1 : 0; // threshold given by ROC
    preds[1] = 1.0 - mu; // class 0
    preds[2] =       mu; // class 1
    return preds;
  }
    public static class BETA implements java.io.Serializable {
      public static final double[] VALUES = new double[6];
      static {
        BETA_0.fill(VALUES);
      }
      static final class BETA_0 implements java.io.Serializable {
        static final void fill(double[] sa) {
          sa[0] = -2.861006627698569E-4;
          sa[1] = -0.8530553146371298;
          sa[2] = 0.6712244655921598;
          sa[3] = 0.02841421204823262;
          sa[4] = 0.7799281401047201;
          sa[5] = -5.75992846938844;
        }
      }
}
// Imputed numeric values
    static class NUM_MEANS implements java.io.Serializable {
      public static final double[] VALUES = new double[5];
      static {
        NUM_MEANS_0.fill(VALUES);
      }
      static final class NUM_MEANS_0 implements java.io.Serializable {
        static final void fill(double[] sa) {
          sa[0] = 66.47528517110267;
          sa[1] = 1.0760456273764265;
          sa[2] = 1.091254752851711;
          sa[3] = 15.928479087452448;
          sa[4] = 6.3536121673003825;
        }
      }
}
// Imputed categorical values.
    static class CAT_MODES implements java.io.Serializable {
      public static final int[] VALUES = new int[0];
      static {
      }
}
    // Categorical Offsets
    public static final int[] CATOFFS = {0};
}
// The class representing training column names
class NamesHolder_glm_binomial_prova_pros_retrain implements java.io.Serializable {
  public static final String[] VALUES = new String[5];
  static {
    NamesHolder_glm_binomial_prova_pros_retrain_0.fill(VALUES);
  }
  static final class NamesHolder_glm_binomial_prova_pros_retrain_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "AGE";
      sa[1] = "RACE";
      sa[2] = "DCAPS";
      sa[3] = "PSA";
      sa[4] = "GLEASON";
    }
  }
}
// The class representing column CAPSULE
class glm_binomial_prova_pros_retrain_ColInfo_5 implements java.io.Serializable {
  public static final String[] VALUES = new String[2];
  static {
    glm_binomial_prova_pros_retrain_ColInfo_5_0.fill(VALUES);
  }
  static final class glm_binomial_prova_pros_retrain_ColInfo_5_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "0";
      sa[1] = "1";
    }
  }
}

